### PR TITLE
Fix #252

### LINKED ISSUE #252: PDF invoice does not appear properly.
**Describe the bug**
PDF invoice does not appear properly. 

**To Reproduce**
1.  PDF invoice appears like this: https://app.screencast.com/lFXiI8HjsnPCT
2. As Per BRD : https://app.screencast.com/iCP6uHJhoQY8E

Some points are missing in the PDF file like Headings in the order table. https://app.screencast.com/3k6jypblcGTfj
Why email address twice?
Company address and logo, the Payment method is missing  
This is not looking good to me. https://app.screencast.com/1oIUnvB0Q6Zuo 

**Expected behavior**
PDF invoice should appear properly.

### PR DESCRIPTION
**Pull request by mital-tyche**
1) Add default label 
2) remove some function comments 
3) Add some function comment for solve PHPCS issue fix #252

### CODE REVIEW

File: includes/wcdn-template-functions.php [hunk 1]
```diff
@@ -323,28 +328,37 @@ function wcdn_get_order_info( $order, $type = '' ) {
...
+	
 
 	if ( isset( $data['order_number']['active'] ) ) {
-		$label                  = $data['order_number']['order_number_text'];
+		if ( isset( $data['order_number']['order_number_text'] ) && ! empty( $data['order_number']['order_number_text'] ) ) {
+			$label = $data['order_number']['order_number_text'];
+		} else {
+			$label = __( 'Order Number', 'woocommerce-delivery-notes' );
+		}
+		$label                  = $label;
```
Comment (pinalj) [inline includes/wcdn-template-functions.php:361]: Why has this redundant line of code been added? It's present at multiple places. Please remove it.

**Comment by mital-tyche** [comment]
Hey @pinal,
if i remove label = label i can i assign label value in label variable. Bcz in every place label = label used for different fields.

**Comment by mital-tyche** [comment]
Please check this [PR](https://github.com/TycheSoftwares/Print-Invoice-Delivery-Notes-for-WooCommerce/pull/272)
