### PR TITLE
Fixed Showing warning on the print invoices.

### LINKED ISSUE #301: Showing warning on the print invoices.
**Describe the bug**
In the print invoice, this warning is coming.

Warning: Trying to access array offset on value of type bool in C:\Users\Nick\Local Sites\print-extra-issue\app\public\wp-content\plugins\Print-Invoice-Delivery-Notes-for-WooCommerce\includes\wcdn-template-functions.php on line 359

Warning: Trying to access array offset on value of type null in C:\Users\Nick\Local Sites\print-extra-issue\app\public\wp-content\plugins\Print-Invoice-Delivery-Notes-for-WooCommerce\includes\wcdn-template-functions.php on line 359

https://prnt.sc/YKg8VbpI2BGB

### PR DESCRIPTION
**Pull request by mokshasharmila13**
Fix #301

### CODE REVIEW

File: includes/wcdn-template-functions.php [hunk 1]
```diff
@@ -356,17 +356,18 @@ function wcdn_get_order_info( $order, $type = '' ) {
 	$fields                = array();
 	$create_invoice_number = get_option( 'wcdn_create_invoice_number' );
 	$data                  = get_option( 'wcdn_' . $type . '_customization' );
-	$template              = $data['template_setting']['template_setting_template'];
+	if ( isset( $data['template_setting'] ) && is_array( $data['template_setting'] ) && isset( $data['template_setting']['template_setting_template'] ) ) {
+		$template = $data['template_setting']['template_setting_template'];
```
Comment (rashmimalpande) [inline includes/wcdn-template-functions.php:360]: Give a default value to $template if $data['template_setting']['template_setting_template'] is not set.

**Review by rashmimalpande — CHANGES_REQUESTED** [review]

File: includes/wcdn-template-functions.php [hunk 2]
```diff
@@ -356,17 +356,16 @@ function wcdn_get_order_info( $order, $type = '' ) {
...
 	$wdn_order_id = ( version_compare( get_option( 'woocommerce_version' ), '3.0.0', '>=' ) ) ? $order->get_id() : $order->id;
 	$order_post   = wc_get_order( $wdn_order_id );
 
-
 	$wdn_order_order_date           = ! is_null( $order->get_date_created() ) ? $order->get_date_created()->getOffsetTimestamp() : '';
 	$wdn_order_payment_method_title = ( version_compare( get_option( 'woocommerce_version' ), '3.0.0', '>=' ) ) ? $order->get_payment_method_title() : $order->payment_method_title;
 	$wdn_order_billing_id           = ( version_compare( get_option( 'woocommerce_version' ), '3.0.0', '>=' ) ) ? $order->get_billing_email() : $order->billing_email;
 	$wdn_order_billing_phone        = ( version_compare( get_option( 'woocommerce_version' ), '3.0.0', '>=' ) ) ? $order->get_billing_phone() : $order->billing_phone;
-	$date_formate                   = get_option('date_format');
+	$date_formate                   = get_option( 'date_format' );
```
Comment (rashmimalpande) [inline includes/wcdn-template-functions.php:368]: @mokshasharmila13 Fix for issue #307 is not present here. Please check it

**Review by rashmimalpande — CHANGES_REQUESTED** [review]

File: includes/wcdn-template-functions.php (hunk 2 above)
Comment (mokshasharmila13) [reply includes/wcdn-template-functions.php:368]: Adding the fix for 307 issue since it was not committed in this issue.

**Review by rashmimalpande — APPROVED** [review]
